### ISSUE TITLE
The XPath query in comments (photoprism /recipe.yaml) is not ignored

### ISSUE THREAD

**Issue by booleeny** [openmediavault/openmediavault-k8s-recipes#7]
Hi,
I executed the recipes/photoprism/recipe.yaml.

Line 86    `   #     path: {{ sharedfolder_path('<NAME>') }} # <<< Replace` is commented but throws an exeption if not completely removed.

`An exception has been thrown during the rendering of a template ("The XPath query '//system/shares/sharedfolder[name='<NAME>']' does not return the requested number of 1 object(s).") in "manifest" at line 86.`

If the import-volume is not used, the comment must be completely removed or otherwise commeted following XPath querys like
(: Houston, we have a problem :)

**Comment by votdev** [comment]
Will be fixed with `openmediavault-k8s 7.2.1`.
